[tool.poetry]
name        = "presentation_blackhat_eu_dec_2025"
version     = "v1.1.1"
description = "presentation_blackhat_eu_dec_2025"
authors     = ["Dinis Cruz <dinis.cruz@owasp.org>"]
license     = "Apache 2.0"
readme      = "README.md"
homepage    = "https://github.com/the-cyber-boardroom/presentation_blackhat_eu_dec_2025"
repository  = "https://github.com/the-cyber-boardroom/presentation_blackhat_eu_dec_2025"

packages    = [
    { include = "presentation_blackhat_eu_dec_2025"         },
    { include = "presentation_blackhat_eu_dec_2025__slides" }
]

[tool.poetry.dependencies]
python                     = "^3.12"
osbot-fast-api-serverless  = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"