[tool.poetry]
name        = "presentation__blackhat-eu__dec-2025"
version     = "v0.6.0"
description = "Presentation__BlackHat-EU__Dec-2025"
authors     = ["Dinis Cruz <dinis.cruz@owasp.org>"]
license     = "Apache 2.0"
readme      = "README.md"
homepage    = "https://github.com/the-cyber-boardroom/Presentation__BlackHat-EU__Dec-2025"
repository  = "https://github.com/the-cyber-boardroom/Presentation__BlackHat-EU__Dec-2025"

[tool.poetry.dependencies]
python                     = "^3.12"
osbot-fast-api-serverless  = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"